{% set name = "readchar" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magmax/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2c3a6eb9a41c228ab8324b7abaff7a91ec5c8c450b5b81f0853b6f0855b9e692
  patches:
    # https://github.com/magmax/python-readchar/issues/122
    - fix_wrong_version.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - GITHUB_REF=refs/tags/v{{ version }}

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - flake8
  run:
    - python >=3.8

test:
  requires:
    - pip
    - m2-git  # [win]
  imports:
    - readchar
  commands:
    - pip check
    - pip list | grep -iE "readchar\s+{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/magmax/python-readchar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily read single chars and key strokes.

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
