{% set name = "readchar" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magmax/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1421f4de65dca84c7bd3565667401b4f6b925e96c93446f7823f8930c2f0e5ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flake8
  run:
    - python >=3.6

test:
  imports:
    - readchar

about:
  home: https://github.com/magmax/python-readchar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily read single chars and key strokes.

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
