{% set name = "readchar" %}
{% set version = "4.2.0" %}

package:
  name: readchar
  version: {{ version }}

source:
  url: https://github.com/magmax/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 48f5810991ecd71c29d390b4489f130dc84fa5922096262e2a0f4418e5e83b0c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  script_env:
   - GITHUB_REF=refs/tags/v{{ version }}

requirements:
  host:
    - pip
    - python >=3.6
    - flake8
  run:
    - python >=3.6

test:
  requires:
    - pip
    - m2-git  # [win]
  imports:
    - readchar
  commands:
    - pip check
    - pip list | grep -iE "readchar\s+{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/magmax/python-readchar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily read single chars and key strokes.

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
